
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    #path('', LoginView.as_view(template_name='index.html'), name='login'),
    path('index/', views.index),
    path('imagenes/', views.imagenes),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('altaEmpleados/', views.altaEmpleados, name='altaEmpleados'),
    path('guardarEmpleado/', views.guardarEmpleado, name='guardarEmpleado'),
    path('listaEmpleados/', views.listaEmpleados, name='listaEmpleados'),
    path('editarEmpleado/<int:id>/', views.editarEmpleado, name='editarEmpleado'),
    path('eliminarEmpleado/<int:id>/', views.eliminarEmpleado, name='eliminarEmpleado'),
    path('guardar', views.guardar, name='guardar'),
    path('login/', views.login, name='login'),
    path ('salir/', views.salir, name='salir'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('evaluaciones/', views.evaluaciones, name='evaluaciones'),
    path('crearEvaluacion/', views.crearEvaluacion, name='crearEvaluacion'),
    path('crearEvaluacion2/', views.crearEvaluacion2, name='crearEvaluacion2'),
    path('crearEvaluacionDB/<str:arregloBonos>/<str:arregloCLs>/<str:arregloKPIs>/<str:arregloOKRs>/', views.crearEvaluacionDB, name='crearEvaluacionDB'),
    path('guardarEvaluacionBD/', views.guardarEvaluacionBD, name='guardarEvaluacionBD'),
    path ('asignarEvaluacion/', views.asignarEvaluacion, name='asignarEvaluacion'),
    path ('obtener_datos_evaluacion/', views.obtener_datos_evaluacion, name='obtener_datos_evaluacion'),
    path ('rutaEvaluacion/', views.rutaEvaluacion, name='rutaEvaluacion'),
    path ('guardarRutaEvaluacion/', views.guardarRutaEvaluacion, name='guardarRutaEvaluacion'),
    path ('obtener_datos_seguimiento/', views.obtener_datos_seguimiento, name='obtener_datos_seguimiento'),
    path ('guardarEvaluacionMensual', views.guardarEvaluacionMensual, name='guardarEvaluacionMensual'),
    path ('guardarEvaluacionEditada', views.guardarEvaluacionEditada, name='guardarEvaluacionEditada'),
    path ('editarEvaluacion/', views.editarEvaluacion, name='editarEvaluacion'),
    path ('obtener_datos_evaluaciones/', views.obtener_datos_evaluaciones, name='obtener_datos_evaluaciones'),
    path ('obtener_datos_evaluaciones_editada/', views.obtener_datos_evaluaciones_editada, name='obtener_datos_evaluaciones_editada'),
    path ('editarEvaluacionAsignada/<int:id>/', views.editarEvaluacionAsignada, name='editarEvaluacionAsignada'),
    path ('comentariosInicio/', views.comentariosInicio, name='comentariosInicio'),
    path ('guardar_comentarios_iniciales/', views.guardar_comentarios_iniciales, name='guardar_comentarios_iniciales'),
    path ('autoevaluacion/', views.autoevaluacion, name='autoevaluacion'),
    path ('obtener_datos_evaluacion_comentarios/', views.obtener_datos_evaluacion_comentarios, name='obtener_datos_evaluacion_comentarios'),
    path ('calendario/', views.calendario, name='calendario'),
    path ('traerDatosEmpleado/', views.traerDatosEmpleado, name='traerDatosEmpleado'),
    path ('informacion/', views.informacion, name='informacion'),
    path ('obtener_datos_evaluacion_autoevaluacion/', views.obtener_datos_evaluacion_autoevaluacion, name='obtener_datos_evaluacion_autoevaluacion'),
    path ('guardarAutoevaluacion/', views.guardarAutoevaluacion, name='guardarAutoevaluacion'),
    path ('porEvaluar/', views.porEvaluar, name='porEvaluar'),
    path ('guardarCalendario/', views.guardarCalendario, name='guardarCalendario'),
    path ('obtener_calendario/', views.obtener_calendario, name='obtener_calendario'),
    path ('editarCalendario/', views.editarCalendario, name='editarCalendario'),
    path ('personaEvaluar/', views.personaEvaluar, name='personaEvaluar'),
    path ('guardarCalificacion/', views.guardarCalificacion, name='guardarCalificacion'),
    path ('guardarAvance/', views.guardarAvance, name='guardarAvance'),
    path ('enviarCorreo/', views.enviarCorreo, name='enviarCorreo'),
    path ('enviarCorreoFin/', views.enviarCorreoFin, name='enviarCorreoFin'),
    path ('reportesEmpleado/', views.reportesEmpleado, name='reportesEmpleado'),
    path ('obtener_reporte_empleados/', views.obtener_reporte_empleados, name='obtener_reporte_empleados'),
    path ('crearEvaluaciones/', views.crearEvaluaciones, name='crearEvaluaciones'),
    path('reportesGenerales/', views.reportesGenerales, name='reportesGenerales'),
    path('generarReporte/', views.generarReporte, name='generarReporte'),
    path('reporte/', views.reporte, name='reporte'),
    path('reporteEvaluacion/<int:id>/', views.reporteEvaluacion, name='reporteEvaluacion'),
    path('guardarDirector/', views.guardarDirector, name='guardarDirector'),
    path('obtener_reporte_empleados_antiguo/', views.obtener_reporte_empleados_antiguo, name='obtener_reporte_empleados_antiguo'),
    path ('obtenerEvaluacionAntigua/<int:id>/', views.obtenerEvaluacionAntigua, name='obtenerEvaluacionAntigua'),
    path ('obtenerEvaluacionAreas/<int:id>/', views.obtenerEvaluacionAreas, name='obtenerEvaluacionAreas'),
    path ('obtenerEvaluacionOKR/<int:id>/', views.obtenerEvaluacionOKR, name='obtenerEvaluacionOKR'),
    path('reporteEvaluacionOKR/<int:id>/', views.reporteEvaluacionOKR, name='reporteEvaluacionOKR'),
    path('validarEvaluacion/<int:id>/<int:tipo>/', views.validarEvaluacion, name='validarEvaluacion'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
