# Generated by Django 3.0.6 on 2024-01-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('valor', models.FloatField()),
                ('estatus', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_autoevaluacion', models.FloatField()),
                ('cal_jefe', models.FloatField()),
                ('cal_administrador', models.FloatField()),
                ('cal_supervisor', models.FloatField()),
                ('cal_director', models.FloatField()),
                ('estatus', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_emp', models.IntegerField(unique=True)),
                ('nombre', models.TextField()),
                ('apellido_paterno', models.TextField()),
                ('apellido_materno', models.TextField()),
                ('correo', models.TextField()),
                ('password', models.TextField()),
                ('estatus', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios_autoevaluado', models.TextField()),
                ('comentarios_jefe', models.TextField()),
                ('comentarios_director', models.TextField()),
                ('comentarios_supervisor', models.TextField()),
                ('comentarios_administrador', models.TextField()),
                ('estatus', models.SmallIntegerField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Calificaciones')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Empleados', to_field='no_emp')),
            ],
        ),
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.SmallIntegerField()),
                ('anio', models.SmallIntegerField()),
                ('estatus', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('metrica', models.TextField()),
                ('valor', models.FloatField()),
                ('estatus', models.SmallIntegerField()),
                ('apartado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Apartados')),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('departamento', models.TextField()),
                ('estatus', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rangos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estatus', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestado_evaludado1', models.BooleanField()),
                ('contestado_evaludado2', models.BooleanField()),
                ('contestado_evaludado3', models.BooleanField()),
                ('contestado_evaludado4', models.BooleanField()),
                ('estatus', models.SmallIntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_empleado', to='Evaluaciones.Empleados', to_field='no_emp')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Fechas')),
                ('id_evaluador1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_evaluador1', to='Evaluaciones.Empleados', to_field='no_emp')),
                ('id_evaluador2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_evaluador2', to='Evaluaciones.Empleados', to_field='no_emp')),
                ('id_evaluador3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_evaluador3', to='Evaluaciones.Empleados', to_field='no_emp')),
                ('id_evaluador4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos_evaluador4', to='Evaluaciones.Empleados', to_field='no_emp')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivosMensuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_autoevaluacion', models.FloatField()),
                ('cal_jefe', models.FloatField()),
                ('cal_director', models.FloatField()),
                ('cal_administrador', models.FloatField()),
                ('cal_supervisor', models.FloatField()),
                ('estatus', models.SmallIntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Empleados', to_field='no_emp')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Evaluaciones')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Fechas')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Objetivos')),
            ],
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Fechas'),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='seguimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Seguimientos'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Puestos'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='rango',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Rangos'),
        ),
        migrations.CreateModel(
            name='ComentariosIndividuales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('estatus', models.SmallIntegerField()),
                ('ObjetivoMensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.ObjetivosMensuales')),
                ('empleadoComentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Empleados', to_field='no_emp')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Fechas')),
            ],
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Empleados', to_field='no_emp'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Evaluaciones.Fechas'),
        ),
    ]
