# Generated by Django 3.0.6 on 2024-02-14 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_auto_20240214_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('valor', models.FloatField()),
                ('estatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActivacion', models.DateField()),
                ('estatus', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Empleados', to_field='no_emp')),
            ],
        ),
        migrations.CreateModel(
            name='Fechas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NumerosEvaluaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.IntegerField()),
                ('fechaCreacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestado1', models.IntegerField()),
                ('contestado2', models.IntegerField()),
                ('contestado3', models.IntegerField()),
                ('contestado4', models.IntegerField()),
                ('estatus', models.IntegerField()),
                ('evaluador1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluador1', to='evaluaciones.Empleados', to_field='no_emp')),
                ('evaluador2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluador2', to='evaluaciones.Empleados', to_field='no_emp')),
                ('evaluador3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluador3', to='evaluaciones.Empleados', to_field='no_emp')),
                ('evaluador4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluador4', to='evaluaciones.Empleados', to_field='no_emp')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Fechas')),
                ('no_emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Empleados', to_field='no_emp')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_autoevaluado', models.FloatField()),
                ('calificacion_evaluador1', models.FloatField()),
                ('calificacion_evaluador2', models.FloatField()),
                ('calificacion_evaluador3', models.FloatField()),
                ('calificacion_evaluador4', models.FloatField()),
                ('calificacion_director', models.FloatField()),
                ('estatus', models.IntegerField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Evaluaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('metrica', models.TextField()),
                ('valor', models.FloatField()),
                ('estatus', models.IntegerField()),
                ('apartado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Apartados')),
                ('numeroEvaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.NumerosEvaluaciones')),
            ],
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Fechas'),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='numeroEvaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.NumerosEvaluaciones'),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='seguimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Seguimiento'),
        ),
        migrations.CreateModel(
            name='ComentariosObjetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fechaComentario', models.DateField()),
                ('estatus', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleadoComentado', to='evaluaciones.Empleados', to_field='no_emp')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Fechas')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Objetivos')),
                ('quienComenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quienComenta', to='evaluaciones.Empleados', to_field='no_emp')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_autoevaluado', models.TextField()),
                ('comentario_evaluador1', models.TextField()),
                ('comentario_evaluador2', models.TextField()),
                ('comentario_evaluador3', models.TextField()),
                ('comentario_evaluador4', models.TextField()),
                ('comentario_director', models.TextField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Evaluaciones')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionesObjetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('fechaCalificacion', models.DateField()),
                ('estatus', models.IntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleadoCalificado', to='evaluaciones.Empleados', to_field='no_emp')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Fechas')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Objetivos')),
                ('quienCalifica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quienCalifica', to='evaluaciones.Empleados', to_field='no_emp')),
            ],
        ),
    ]
