# Generated by Django 3.0.6 on 2024-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_auto_20240214_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='no_emp',
            field=models.IntegerField(default=1, unique=True, verbose_name='employee number'),
            preserve_default=False,
        ),
    ]
