# Generated by Django 3.0.6 on 2024-02-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_usuarios_no_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='no_emp',
        ),
    ]
