# Generated by Django 3.0.6 on 2024-02-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_auto_20240216_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='contestado1',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='contestado2',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='contestado3',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='contestado4',
        ),
    ]
