# Generated by Django 3.0.6 on 2024-02-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_auto_20240216_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estatus', models.IntegerField()),
            ],
        ),
    ]
