# Generated by Django 3.0.6 on 2024-02-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_fases'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='fase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Fases'),
            preserve_default=False,
        ),
    ]
