# Generated by Django 3.0.6 on 2024-03-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_evaluaciones_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionesobjetivos',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='comentariosobjetivos',
            name='empleado',
        ),
        migrations.AddField(
            model_name='calificacionesobjetivos',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Evaluaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentariosobjetivos',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='evaluaciones.Evaluaciones'),
            preserve_default=False,
        ),
    ]
