# Generated by Django 3.0.6 on 2024-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0009_auto_20240304_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentariosInicialesInicio', models.DateField()),
                ('comentariosInicialesFin', models.DateField()),
                ('empleadosInicio', models.DateField()),
                ('empleadosFin', models.DateField()),
                ('evaluadoresInicio', models.DateField()),
                ('evaluadoresFin', models.DateField()),
                ('tipo', models.IntegerField()),
                ('estatus', models.IntegerField()),
            ],
        ),
    ]
