# Generated by Django 3.0.6 on 2024-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0010_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='comentario_capitalHumano',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
