# Generated by Django 3.0.6 on 2024-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0011_comentarios_comentario_capitalhumano'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='estatus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentarios',
            name='logros',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
